# Generated by Django 5.1.7 on 2025-03-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djasana', '0026_alter_attachment_download_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstatus',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectstatus',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
