# Generated by Django 5.1.7 on 2025-03-10 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djasana', '0028_alter_customfield_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='enum_options',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
    ]
